<a href="https://colab.research.google.com/github/Midhilesh4890/Topic-Modelling/blob/main/Topic_Modelling_using_Scikit_Learn_LDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition
import matplotlib.pyplot as plt
import numpy as np
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer 
from sklearn.model_selection import train_test_split

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
df=pd.read_csv('https://github.com/Midhilesh4890/Topic-Modelling/blob/main/consumer_compliants.zip?raw=true', compression='zip', sep=',', quotechar='"')

In [ ]:
df

Date received  ... Complaint ID
0          4/3/2020  ...      3591341
1         3/12/2020  ...      3564184
2          2/6/2020  ...      3521949
3          3/6/2020  ...      3556237
4         2/14/2020  ...      3531704
...             ...  ...          ...
57448     2/29/2020  ...      3549178
57449     2/11/2020  ...      3527928
57450     2/29/2020  ...      3549238
57451     1/16/2020  ...      3498566
57452     1/16/2020  ...      3498524

[57453 rows x 18 columns]

In [ ]:
df['Product'].value_counts()

Debt collection                21772
Credit card or prepaid card    13193
Mortgage                        9799
Checking or savings account     7003
Student loan                    2950
Vehicle loan or lease           2736
Name: Product, dtype: int64

In [ ]:
df['Company'].value_counts()

CITIBANK, N.A.                           3226
CAPITAL ONE FINANCIAL CORPORATION        2711
BANK OF AMERICA, NATIONAL ASSOCIATION    2580
JPMORGAN CHASE & CO.                     2409
WELLS FARGO & COMPANY                    2001
                                         ... 
LPSG                                        1
Certified Recovery Inc                      1
Cooper Hoffman Klein Associates             1
Gryphon Corp.                               1
Credit Wise Recovery Solution LLC           1
Name: Company, Length: 2197, dtype: int64

In [ ]:
complaints_df = df[['Consumer complaint narrative','Product','Company']].rename(columns={'Consumer complaint narrative':'complaints'})

In [ ]:
pd.set_option('display.max_colwidth', -1)
complaints_df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


complaints  ...                                                      Company
0      This auto loan was opened on XX/XX/2020 in XXXX, NC with BB & T in my name. I have NEVER been to North Carolina and I have NEVER been a resident. I have filed a dispute twice through my credit bureaus but both times BB & T has claimed that this is an accurate loan. Which I wasn't aware of until today. I have tried to contact BB & T multiple times but I have never gotten through to a live person. I do n't drive and I have never owned a car before. I didn't have any knowledge of this account until I checked XXXXXXXX XXXX  and noticed it. I've tried twice to dispute it. Additionally I never received any bills or information about this account. This is my last resort in trying to remove this fraudulent loan off of my account.                                                                                                                                                                                                                                                                                                                                                                                             ...  TRUIST FINANCIAL CORPORATION                               
1      In XXXX of 2019 I noticed a debt for {$620.00} on my credit which i believed was mine I thought speedy cash had bought one of my old debts and sold it to XXXX XXXX XXXX XXXX. I contacted XXXX XXXX XXXX XXXX and after several attempts of giving my full name, nothing came up in their system. I gave my social and the rep said the account popped up but DID NOT tell me that the account was under someone elses name and continued to let me make a payment. The payment was for {$120.00}. Confirmation number-XXXX. After realizing it was not my account, I called back to get my money back and inform them of the mistake. I was told i needed to mail them an FTC report and dispute letter to get my money back. I completed all of this and when i called again they said they transferred the account back to speedy cash for fraud review and I would need to contact them. After contacting them i was again told that i can not get my money back. The issue im having is this representative at XXXX XXXX played blind to obvious fraud and let an innocent person make a payment on someone elses debt and i want my money back.  ...  CURO Intermediate Holdings                                 
2      As stated from Capital One, XXXX XX/XX/XXXX and XXXX 2018, My wife and I went to several car dealerships to request for a car loan to get a used car. However, according to their credit requirements unfortunately my credit score was insufficient for the car loan approval at that time. It seemed as though they pulled my credit report multiple times.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...  CAPITAL ONE FINANCIAL CORPORATION                          
3      Please see CFPB case XXXX. \n\nCapital One, in the letter they provided ( and attached to that case as their response ) said this : " The funds were reversed and sent back to XXXX XXXX XXXX  on XX/XX/XXXX ''. \n\nXXXX XXXX XXXX  ( now XXXX XXXX  ) has not received these funds. Staff at XXXX XXXX  - and also staff at the account-holder 's business - have looked f

In [ ]:
X_train, X_test = train_test_split(complaints_df, test_size=0.6, random_state=111)

In [ ]:
X_train['Product'].value_counts()

Debt collection                8720
Credit card or prepaid card    5297
Mortgage                       3809
Checking or savings account    2822
Student loan                   1236
Vehicle loan or lease          1097
Name: Product, dtype: int64

In [ ]:
stemmer = SnowballStemmer(language='english')

In [ ]:
def tokenize(text):
   tokens = [word for word in nltk.word_tokenize(text) if (len(word) > 3 and len(word.strip('Xx/')) > 2) ] 
   stems = [stemmer.stem(item) for item in tokens]
   return tokens

In [ ]:
vectorizer_tf = TfidfVectorizer(tokenizer=tokenize, stop_words='english', max_df=0.75, min_df=50, max_features=10000, use_idf=False, norm=None)
tf_vectors = vectorizer_tf.fit_transform(X_train.complaints) 

In [ ]:
tf_vectors.A

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tf_vectors.A.shape

(22981, 2967)

In [ ]:
vectorizer_tf.get_feature_names()

['0.00',
 '1.00',
 '10.00',
 '100.00',
 '1000.00',
 '10000.00',
 '100000.00',
 '110.00',
 '1100.00',
 '11000.00',
 '12.00',
 '120.00',
 '1200.00',
 '12000.00',
 '130.00',
 '1300.00',
 '13000.00',
 '140.00',
 '1400.00',
 '14000.00',
 '15.00',
 '150.00',
 '1500.00',
 '15000.00',
 '160.00',
 '1600.00',
 '16000.00',
 '1681c-2',
 '1692',
 '1692g',
 '170.00',
 '1700.00',
 '180.00',
 '1800.00',
 '18000.00',
 '190.00',
 '1900.00',
 '2.00',
 '20.00',
 '200.00',
 '2000.00',
 '20000.00',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2019.',
 '2020',
 '210.00',
 '2100.00',
 '220.00',
 '2200.00',
 '230.00',
 '2300.00',
 '240.00',
 '2400.00',
 '25.00',
 '250.00',
 '2500.00',
 '25000.00',
 '260.00',
 '2600.00',
 '27.00',
 '270.00',
 '2700.00',
 '28.00',
 '280.00',
 '2800.00',
 '29.00',
 '290.00',
 '2900.00',
 '3.00',
 '30.00',
 '300.00',
 '3000.00',
 '30000.00',
 '310.00',
 '320.00',
 '3200.00',
 '3300.00',
 '340.00',
 '3400.00',
 '35.00',
 '350.00',
 '3500.00',
 '36.00',
 '360.00',
 '3600.00',
 '37

In [ ]:
lda = decomposition.LatentDirichletAllocation(n_components=6, max_iter=3, learning_method='online', learning_offset=50, n_jobs=-1, random_state=111)
W1 = lda.fit_transform(tf_vectors)
H1 = lda.components_

In [ ]:
W1 ##The values are like weights given to the 6 topics as we have given n_components = 6 in each document

array([[0.40182055, 0.00119634, 0.20577477, 0.29858583, 0.0011919 ,
        0.09143062],
       [0.00126332, 0.05483517, 0.67769433, 0.26368021, 0.00126195,
        0.00126502],
       [0.11339717, 0.00559696, 0.18965242, 0.68015024, 0.00559755,
        0.00560566],
       ...,
       [0.07437239, 0.00304815, 0.24242365, 0.67402458, 0.00306407,
        0.00306716],
       [0.01685243, 0.01673817, 0.9156112 , 0.01690722, 0.01690215,
        0.01698884],
       [0.19539276, 0.66819962, 0.00137129, 0.00137083, 0.13228202,
        0.00138348]])

In [ ]:
H1 ##Words which repeated most times in each topic

array([[3.15658504e+02, 6.77013371e+01, 6.82482643e+01, ...,
        1.69126603e-01, 1.91639462e-01, 7.89483799e+01],
       [6.79100999e-01, 2.10118275e-01, 1.67575084e-01, ...,
        5.35400285e+01, 1.99473435e+01, 3.72037685e+01],
       [1.02113992e+02, 1.25354960e+02, 6.93709938e+01, ...,
        4.26348449e+01, 1.67777977e-01, 9.81826530e+01],
       [1.88002744e+01, 1.96844962e+01, 1.22966223e+01, ...,
        4.22678044e+01, 6.21932566e+01, 7.35092890e+01],
       [8.59930462e+00, 1.67774037e-01, 1.67422387e-01, ...,
        3.52104697e+01, 1.79702263e-01, 4.25939798e+00],
       [8.18577291e+01, 1.79385853e-01, 4.71628510e+00, ...,
        6.95494040e-01, 4.39682952e+01, 6.45914709e+01]])

In [ ]:
num_words=15
vocab = np.array(vectorizer_tf.get_feature_names())
top_words = lambda t: [vocab[i] for i in np.argsort(t)[:-num_words-1:-1]]

In [ ]:
vocab

array(['0.00', '1.00', '10.00', ..., 'york', 'young', 'zero'],
      dtype='<U19')

In [ ]:
topic_words = ([top_words(t) for t in H1])
topics = [' '.join(t) for t in topic_words]

In [ ]:
topic_words

[['payment',
  'paid',
  'balance',
  'account',
  'fees',
  'insurance',
  'payments',
  'late',
  'statement',
  'received',
  'company',
  'charged',
  'month',
  'make',
  'escrow'],
 ['loan',
  'mortgage',
  'home',
  'property',
  'received',
  'letter',
  'sent',
  'documents',
  'time',
  'company',
  'modification',
  'process',
  'servicing',
  'closing',
  'request'],
 ['card',
  'credit',
  'account',
  'bank',
  'charges',
  'dispute',
  'charge',
  'capital',
  'fraud',
  'citi',
  'received',
  'xx/xx/2019',
  'closed',
  'chase',
  'citibank'],
 ['account',
  'bank',
  'told',
  'called',
  'said',
  'phone',
  'money',
  'number',
  'asked',
  'check',
  'received',
  'time',
  'information',
  'funds',
  'email'],
 ['debt',
  'credit',
  'account',
  'collection',
  'report',
  'company',
  'information',
  'reporting',
  'letter',
  'sent',
  'agency',
  'provide',
  'received',
  'original',
  'identity'],
 ['credit',
  'payment',
  'payments',
  'late',
  'time',
 

In [ ]:
topics

['payment paid balance account fees insurance payments late statement received company charged month make escrow',
 'loan mortgage home property received letter sent documents time company modification process servicing closing request',
 'card credit account bank charges dispute charge capital fraud citi received xx/xx/2019 closed chase citibank',
 'account bank told called said phone money number asked check received time information funds email',
 'debt credit account collection report company information reporting letter sent agency provide received original identity',
 'credit payment payments late time month years loans loan told months make help account score']

In [ ]:
colnames = ["Topic" + str(i) for i in range(lda.n_components)]
docnames = ["Doc" + str(i) for i in range(len(X_train.complaints))]
df_doc_topic = pd.DataFrame(np.round(W1, 2), columns=colnames, index=docnames)
significant_topic = np.argmax(df_doc_topic.values, axis=1)
df_doc_topic['dominant_topic'] = significant_topic

In [ ]:
df_doc_topic

Topic0  Topic1  Topic2  Topic3  Topic4  Topic5  dominant_topic
Doc0      0.40    0.00    0.21    0.30    0.00    0.09    0             
Doc1      0.00    0.05    0.68    0.26    0.00    0.00    2             
Doc2      0.11    0.01    0.19    0.68    0.01    0.01    3             
Doc3      0.00    0.00    0.00    0.44    0.55    0.00    4             
Doc4      0.00    0.00    0.00    0.19    0.79    0.00    4             
...        ...     ...     ...     ...     ...     ...   ..             
Doc22976  0.00    0.00    0.75    0.24    0.00    0.00    2             
Doc22977  0.00    0.06    0.23    0.24    0.17    0.30    5             
Doc22978  0.07    0.00    0.24    0.67    0.00    0.00    3             
Doc22979  0.02    0.02    0.92    0.02    0.02    0.02    2             
Doc22980  0.20    0.67    0.00    0.00    0.13    0.00    1             

[22981 rows x 7 columns]

In [ ]:
Wtest = lda.transform(vectorizer_tf.transform(X_test.complaints[:5]))

In [ ]:
colnames = ["Topic" + str(i) for i in range(lda.n_components)]
docnames = ["Doc" + str(i) for i in range(len(X_test.complaints[:5]))]
df_doc_topic = pd.DataFrame(np.round(Wtest, 2), columns=colnames, index=docnames)
significant_topic = np.argmax(df_doc_topic.values, axis=1)
df_doc_topic['dominant_topic'] = significant_topic

In [ ]:
df_doc_topic

Topic0  Topic1  Topic2  Topic3  Topic4  Topic5  dominant_topic
Doc0  0.11    0.00    0.09    0.80    0.00    0.00    3             
Doc1  0.19    0.56    0.00    0.15    0.09    0.00    1             
Doc2  0.22    0.01    0.41    0.36    0.01    0.01    2             
Doc3  0.00    0.29    0.00    0.00    0.00    0.70    5             
Doc4  0.27    0.00    0.18    0.15    0.00    0.39    5